### ISSUE TITLE
Outdated manifest for v2.6

### ISSUE THREAD

**Issue by HippocampusGirl** [chrisfilo/docker2singularity#136]
I am using `docker2singularity` to build "simg" images for compatibility, and it's been working super well for the past years. Thanks for maintaining this resource! 

We require compatibility with v2.6, because the [NeuroDebian repositories still use Singularity v2.6](https://neuro.debian.net/pkgs/singularity-container.html), meaning there are many neuroscientists out there relying on "simg" images for their work. 

Unfortunately, the v2.6 images from quay.io do not work anymore with recent Docker versions due to a [deprecation of the image manifest schema version used](https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1). Here's my error log:
```
$ docker run \
    --privileged \
    --rm \
    --volume="/var/run/docker.sock:/var/run/docker.sock" \
    --volume="$(pwd)/singularity-2:/output" \
    quay.io/singularity/docker2singularity:v2.6 \
    --name ramp-latest.sif \
    ramp:latest
Unable to find image 'quay.io/singularity/docker2singularity:v2.6' locally
v2.6: Pulling from singularity/docker2singularity
docker: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/singularity/docker2singularity:v2.6 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at [https://docs.docker.com/go/deprecated-image-specs/.](https://docs.docker.com/go/deprecated-image-specs/)
See 'docker run --help'.
```

Notably, the [deprecated images on Docker Hub](https://hub.docker.com/r/singularityware/docker2singularity) somehow do not have this problem. Would it be possible to push updated images to quay.io as well?

**Comment by vsoch** [comment]
Oh wow - 2.6 - that's a blast from the past! As long as we can do a rebuild (with a recent docker) I think it should be possible to update the images. I think this is more a registry choice and nothing about the images actually being different. Let me see if I can dig up the old Dockerfile and rebuild and push 2.6 to quay.io. Is that the only version you need?

**Comment by vsoch** [comment]
All set! That was easy - we have all the releases as tags (branches) here so I just had to clone and build :) Would you mind testing `quay.io/singularity/docker2singularity:v2.6-test`? If that works I can push the same 2.6 tag (I take it the one that is present doesn't work at all, so would be OK to remove).

**Comment by HippocampusGirl** [comment]
Hi @vsoch,

Thank you so much for the quick response! I can confirm that the test image works with a recent Docker version :-)
```
# docker run quay.io/singularity/docker2singularity:v2.6-test
Unable to find image 'quay.io/singularity/docker2singularity:v2.6-test' locally
v2.6-test: Pulling from singularity/docker2singularity
e7c96db7181b: Pull complete
5297bd381816: Pull complete
3a664477889c: Pull complete
456ccbcfb7c2: Pull complete
be49115c409f: Pull complete
4e5a67a694a2: Pull complete
e42fcb2f6846: Pull complete
7a20dfb4736b: Pull complete
324ea20f7589: Pull complete
3f2240eaa200: Pull complete
38e399dacd00: Pull complete
Digest: sha256:56da928e5f20654c04844f24d8cda579431587c8b943dbb01da0550daf9bc564
Status: Downloaded newer image for quay.io/singularity/docker2singularity:v2.6-test
USAGE: docker2singularity [-m "/mount_point1 /mount_point2"] [options] docker_image_name

OPTIONS:

          Image Format
              --folder   -f   build development sandbox (folder)
              --writable -w   non-production writable image (ext3)
                              Default is squashfs (recommended)
              --name     -n   provide basename for the container (default based on URI)
              --mount    -m   provide list of custom mount points (in quotes!)
              --help     -h   show this help and exit


```

And yes, version 2.6 is the only one I need.

**Comment by vsoch** [comment]
Pushed!

```bash
docker push quay.io/singularity/docker2singularity:v2.6
```
Let me know if you need any other versions built, and if not, thanks for stopping by and feel free to close the issue. 
And it gives me a lot of joy that a community is still using this little tool! It is almost a decade old at this point. The repository here just has the docker wrapper, but the actual script was something I wrote in 2015.

**Comment by HippocampusGirl** [comment]
It works now, thank you so much :-)
